language: python

matrix:
  fast_finish: true
  include:
    - sudo: false
      script:
         - ./mach test-tidy --no-progress --all
         - ./mach test-tidy --no-progress --self-test
         - python ./etc/memory_reports_over_time.py --test
         - bash etc/ci/check_no_panic.sh
      cache: false
    - sudo: 9000
      dist: trusty
      before_install:
        - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
        - source ~/.profile
      script:
         # see https://github.com/servo/servo/issues/20664
         #- ./mach cargo check -p compositing --no-default-features
         - ./mach build -d --verbose
         - ./mach test-unit
         - ./mach clean
         - bash etc/ci/lockfile_changed.sh
      cache:
        directories:
          - .servo
          - $HOME/.cargo
          - $HOME/.rustup
          - $HOME/.ccache
      before_cache:
        - ./mach clean-nightlies --keep 2 --force
        - ./mach clean-cargo-cache --keep 2 --force
      env:
        CC=gcc-6
        CXX=g++-6
        CCACHE=/usr/bin/ccache
        RUSTFLAGS=-Dwarnings
        CARGO_INCREMENTAL=0
        LLVM_CONFIG=/usr/lib/llvm-3.9/bin/llvm-config
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - autoconf2.13
            - clang-3.9
            - llvm-3.9
            - llvm-3.9-runtime
            - cmake
            - g++-6
            - gperf
            - libosmesa6-dev
            - libgles2-mesa-dev
            - python-virtualenv
            - xorg-dev
            - ccache
            - libdbus-glib-1-dev
            - libedit-dev

branches:
  only:
    - master
